### PR TITLE
Adding support MFA (assumerole)

### PR DESCRIPTION
**Pull request by perriea**
All in the title :)

### CODE REVIEW

**Comment by TylerBrock** [comment]
Awesome, thank you!

Question about the change: Is this something that is usually enabled always as opposed to a flag or special configuration option?

I guess if MFA is required it does the right thing requesting input from stdin and otherwise doesn’t change anything but I want to make sure my assumption is correct.

**Comment by perriea** [comment]
Not in the case of the role switch of Amazon because the sdk looks if you have the line `mfa_serial` on the selected profile. It's pretty clean.

Without MFA : 
```
./saw get PROD_FRONT_APP_LGROUP --start -24h --profile profile_test --region eu-west-1 
2018-06-28 19:06:12,402 ERROR [XNIO-2 task-42] ExceptionMapperStandardImpl: HHH000346: Error during managed flush [org.hibernate.PersistentObjectException: detached entity passed to persist: com.ulysse.domain.Colis]
```

With MFA : 
```
./saw get PROD_FRONT_APP_LGROUP --start -24h --profile profile_mfa --region eu-west-1 
Assume Role MFA token code: 693662
2018-06-28 19:06:12,402 ERROR [XNIO-2 task-42] ExceptionMapperStandardImpl: HHH000346: Error during managed flush [org.hibernate.PersistentObjectException: detached entity passed to persist: com.ulysse.domain.Colis]
```

In my case it works well 👍

**Comment by TylerBrock** [comment]
Killer. Thanks for the code and taking the time to explain. I’m sure a lot of people will appreciate this.

**Comment by TylerBrock** [comment]
I’ll cut v0.1.6 for this feature shortly.

**Comment by perriea** [comment]
@TylerBrock wait a bit I'll clean some parts ;)

**Comment by TylerBrock** [comment]
Whoops I thought you were done? Was there something we missed?

**Pull request merged**
